"""Regenerate dev/embed-test-python.html and dev/python-payload.json
(the csv_grid emitter fixtures; both are committed).

Run from the repo root:
    uv run --project python dev/make-embed-test-python.py

The HTML page is fully self-contained (each fragment inlines the assets
via an idempotent <head> guard) so it works from file:// too, and the two
inline grids are the canary for the 3.3.1 fix: clearing/re-running a cell
can't strip a shared <style>, because there isn't one — the assets live in
<head>, deduped by sentinel. (assets=False is the manual escape hatch for
when you know the assets are already present.) python-payload.json is the
pandas -> JSON half of the round-trip; dev/smoke-test.mjs feeds it to the
grid's normalizeRecords and checks inference + formatting.
"""

import json
from pathlib import Path

import pandas as pd
from csv_grid import __version__, payload, to_html

root = Path(__file__).resolve().parent

df = pd.DataFrame({
    "line": ["GL", "Property", "WC", "Auto", "Marine"],
    "premium": [12_500_000, 8_200_000, 15_750_000, None, 3_100_000],
    "loss_ratio": [0.625, 0.481, 0.7125, 1.05, float("nan")],
    "year": [1995, 2005, 2020, 2024, 2024],
    "written": pd.to_datetime(
        ["1995-03-15", "2005-07-01", "2020-01-31", "2024-06-12", "2024-02-29"]),
    "rate": [1.05, 0.98, 1.12, 1.0, 1.03],
    # sub-second stamps: exercises full-precision emit + the grid's
    # finest-present collapse (this column -> 3-dp ms, .125 forces F=3)
    "stamp": pd.to_datetime(
        ["2024-01-01 09:00:00.500", "2024-01-01 09:00:00.250",
         "2024-01-01 09:00:00.125", "2024-01-01 09:00:01.000",
         "2024-01-01 09:00:02.000"]),
})

frag1 = to_html(df, name="portfolio.df", assets="inline")
frag2 = to_html(
    df,
    assets="inline",                  # also inline: head guard dedupes
    theme="light",                    # force light regardless of OS theme
    align="l--c",                     # center the year column
    # last spec is a date pattern (strftime) on the sub-second stamp column
    formats=[None, ",.0f", ".1%", "year", None, ",.2f", "%H:%M:%S.%f"],
    global_search=False,
    status_bar=False,
)

(root / "embed-test-python.html").write_text(f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>csv_grid python emitter test</title>
    <!-- GENERATED by dev/make-embed-test-python.py (csv_grid v{__version__})
         — do not edit. Self-contained (assets head-injected): file:// works. -->
    <style>
        body {{ margin: 2rem; background: #f4f4f4; font-family: system-ui, sans-serif; }}
        h2 {{ font-size: 1rem; }}
        .pane {{ max-width: 900px; margin-bottom: 2.5rem; }}
    </style>
</head>
<body>
<h1 style="font-size:1.3rem">csv_grid python emitter test — two to_html() fragments</h1>
<div class="pane">
<h2>1 — defaults, assets inlined (NaN premium/loss_ratio -> blank,
    integral floats -> ints, dates ISO)</h2>
{frag1}
</div>
<div class="pane">
<h2>2 — second inline grid (head guard dedupes the assets), theme='light',
    align 'l--c', formats [None, ',.0f', '.1%', 'year', None, ',.2f'],
    no search/status</h2>
{frag2}
</div>
</body>
</html>
""", encoding="utf-8")

(root / "python-payload.json").write_text(
    json.dumps(payload(df, name="portfolio.df"), indent=1), encoding="utf-8")

print(f"wrote embed-test-python.html + python-payload.json (csv_grid v{__version__})")
